import { halfLogo } from "../images";

// item.menu
// // .image
// .minPrice
// .menuDetail
// .delivTip

export default [
  {
    id: "1",
    category: "중식",
    menu: "메뉴메뉴",
    menuDetail: "디테일디테일",
    minPrice: 10000,
    image: "https:",
    imageLocal: halfLogo,
    delivTip: 5000,
  },
  {
    id: "2",
    category: "카페",
    menu: "메뉴메뉴",
    menuDetail: "디테일디테일",
    minPrice: 12000,
    image: "",
    imageLocal: halfLogo,
    delivTip: 6000,
  },
  {
    id: "3",
    category: "한식",
    menu: "메뉴메뉴",
    menuDetail: "디테일디테일",
    minPrice: 8000,
    image: "",
    imageLocal: halfLogo,
    delivTip: 3000,
  },

  {
    id: "4",
    category: "일식",
    menu: "메뉴메뉴",
    menuDetail: "디테일디테일",
    minPrice: 20000,
    image: "==",
    imageLocal: halfLogo,
    delivTip: 5000,
  },
  {
    id: "5",
    category: "일식",
    menu: "메뉴메뉴",
    menuDetail: "디테일디테일",
    minPrice: 12000,
    image: "",
    imageLocal: halfLogo,
    delivTip: 5000,
  },
  {
    id: "6",
    category: "한식",
    menu: "메뉴메뉴",
    menuDetail: "디테일디테일",
    minPrice: 5000,
    image: "==",
    imageLocal: halfLogo,
    delivTip: 1000,
  },
  {
    id: "7",
    category: "한식",
    menu: "메뉴메뉴",
    menuDetail: "디테일디테일",
    minPrice: 12000,
    image: "",
    imageLocal: halfLogo,
    delivTip: 3000,
  },
  {
    id: "8",
    category: "양식",
    menu: "메뉴메뉴",
    menuDetail: "디테일디테일",
    minPrice: 18000,
    image: "",
    imageLocal: halfLogo,
    delivTip: 3000,
  },
  {
    id: "9",
    category: "한식",
    menu: "메뉴메뉴",
    menuDetail: "디테일디테일",
    minPrice: 18000,
    image: "",
    imageLocal: halfLogo,
    delivTip: 3000,
  },
  {
    id: "10",
    category: "카페",
    menu: "메뉴메뉴",
    menuDetail: "디테일디테일",
    minPrice: 16000,
    image: "==",
    imageLocal: halfLogo,
    delivTip: 3000,
  },
];
